sudo: false
language: python
python:
    - '2.7'
    - '3.2'
    - '3.3'
    - '3.4'
    - '3.5'

# command to install dependencies
install:
    - pip install . 
    - pip install -r tests/requirements.txt 
    - pip install coveralls flake8

# command to run tests
script:
    - py.test stl tests

after_success:
        - coveralls

before_script: flake8 --ignore=W391 stl tests

after_success:
    - coveralls

